{
 "openapi": "3.1.0",
 "info": {
  "title": "Learning Path Platform",
  "version": "0.0.1",
  "description": "Learning Path Platform"
 },
 "servers": [
  {
   "url": "https://lpp.home.russfeld.me/"
  }
 ],
 "paths": {
  "/api/": {
   "get": {
    "summary": "list API versions",
    "tags": [
     "api"
    ]
   }
  },
  "/auth/bypass": {
   "get": {
    "summary": "bypass authentication for testing",
    "description": "Bypasses CAS authentication for testing purposes",
    "tags": [
     "auth"
    ]
   }
  },
  "/auth/cas": {
   "get": {
    "summary": "CAS authentication",
    "description": "CAS authentication for deployment",
    "tags": [
     "auth"
    ]
   }
  },
  "/auth/token": {
   "get": {
    "summary": "request JWT",
    "description": "request JWT based on previous authentication",
    "tags": [
     "auth"
    ]
   }
  },
  "/auth/logout": {
   "get": {
    "summary": "logout current user",
    "description": "logout current user and end session",
    "tags": [
     "auth"
    ]
   }
  },
  "/lti/": {
   "get": {
    "summary": "list LTI routes",
    "tags": [
     "lti"
    ]
   }
  },
  "/api/v1/consumers": {
   "get": {
    "summary": "consumers list page",
    "description": "Gets the list of all consumers in the application",
    "tags": [
     "consumers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   },
   "post": {
    "summary": "create consumer",
    "tags": [
     "consumers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   }
  },
  "/api/v1/consumers/{id}": {
   "put": {
    "summary": "update consumer",
    "tags": [
     "consumers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete consumer",
    "tags": [
     "consumers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   }
  },
  "/api/v1/courses": {
   "get": {
    "summary": "courses list page",
    "description": "Gets the list of all courses in the application",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   },
   "post": {
    "summary": "create course",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   }
  },
  "/api/v1/courses/{id}": {
   "get": {
    "summary": "get single course",
    "description": "Gets a single course by ID",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   },
   "put": {
    "summary": "update course",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete course",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   }
  },
  "/api/v1/courses/{id}/link": {
   "post": {
    "summary": "link an LMS course to an existing course",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ],
    "content": {
     "application/json": {
      "schema": {
       "type": "object",
       "required": [
        "destID"
       ],
       "properties": {
        "destID": {
         "type": "integer",
         "description": "ID of the destination course"
        }
       }
      }
     }
    }
   }
  },
  "/api/v1/courses/{id}/users": {
   "get": {
    "summary": "get users for a course",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   }
  },
  "/api/v1/courses/{id}/enroll": {
   "post": {
    "summary": "enroll a user in a course",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   }
  },
  "/api/v1/courses/{id}/remove": {
   "post": {
    "summary": "remove a user from a course",
    "tags": [
     "courses"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_courses"
      ]
     }
    ]
   }
  },
  "/api/v1/lessons": {
   "get": {
    "summary": "lessons list page",
    "description": "Gets the list of all lessons in the application",
    "tags": [
     "lessons"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lessons"
      ]
     }
    ]
   },
   "post": {
    "summary": "create lesson",
    "tags": [
     "lessons"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lessons"
      ]
     }
    ]
   }
  },
  "/api/v1/lessons/{id}": {
   "put": {
    "summary": "update lesson",
    "tags": [
     "lessons"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lessons"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete lesson",
    "tags": [
     "lessons"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lessons"
      ]
     }
    ]
   }
  },
  "/api/v1/lessons/{id}/form": {
   "get": {
    "summary": "lesson form",
    "description": "Gets the LTI form for a lesson",
    "tags": [
     "lessons"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lessons"
      ]
     }
    ]
   }
  },
  "/api/v1/levels": {
   "get": {
    "summary": "levels list page",
    "description": "Gets the full list of levels",
    "tags": [
     "levels"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher",
       "manage_lessons"
      ]
     }
    ]
   }
  },
  "/api/v1/profile": {
   "get": {
    "summary": "current user profile",
    "description": "Gets the current user's profile",
    "tags": [
     "profile"
    ],
    "security": [
     {
      "bearerAuth": null
     }
    ]
   },
   "post": {
    "summary": "update profile",
    "tags": [
     "profile"
    ],
    "security": [
     {
      "bearerAuth": null
     }
    ]
   }
  },
  "/api/v1/providers": {
   "get": {
    "summary": "providers list page",
    "description": "Gets the list of all providers in the application",
    "tags": [
     "providers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti",
       "manage_lessons"
      ]
     }
    ]
   },
   "post": {
    "summary": "create provider",
    "tags": [
     "providers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   }
  },
  "/api/v1/providers/{id}": {
   "put": {
    "summary": "update provider",
    "tags": [
     "providers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete provider",
    "tags": [
     "providers"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   }
  },
  "/api/v1/roles": {
   "get": {
    "summary": "roles list page",
    "description": "Gets the list of all roles in the application",
    "tags": [
     "roles"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   }
  },
  "/api/v1/sections": {
   "get": {
    "summary": "sections list page",
    "description": "Gets the list of all sections in the application",
    "tags": [
     "sections"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lessons"
      ]
     }
    ]
   },
   "post": {
    "summary": "create section",
    "tags": [
     "sections"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   }
  },
  "/api/v1/sections/{id}": {
   "put": {
    "summary": "update section",
    "tags": [
     "sections"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_sections"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete section",
    "tags": [
     "sections"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_sections"
      ]
     }
    ]
   }
  },
  "/api/v1/student/assignments/{id}": {
   "get": {
    "summary": "assignment information",
    "description": "Gets information about a particular assignment for a student",
    "tags": [
     "student"
    ],
    "security": [
     {
      "bearerAuth": [
       "student"
      ]
     }
    ]
   }
  },
  "/api/v1/student/assignments/{id}/outcomes/{outcomeid}/lessons/{lessonid}": {
   "get": {
    "summary": "lesson information",
    "description": "Gets information about a particular lesson for a student",
    "tags": [
     "student"
    ],
    "security": [
     {
      "bearerAuth": [
       "student"
      ]
     }
    ]
   }
  },
  "/api/v1/student/assignments/{id}/outcomes/{outcomeid}/lessons/{lessonid}/form": {
   "get": {
    "summary": "lesson information",
    "description": "Gets information about a particular lesson for a student",
    "tags": [
     "student"
    ],
    "security": [
     {
      "bearerAuth": [
       "student"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses": {
   "get": {
    "summary": "courses list page",
    "description": "Gets the list of all courses for this teacher",
    "tags": [
     "teacher"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/assignments": {
   "get": {
    "summary": "courses list page",
    "description": "Gets the list of assignments for this course",
    "tags": [
     "teacher"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   },
   "post": {
    "summary": "save assignment",
    "tags": [
     "assignments"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/assignments/{assignid}": {
   "get": {
    "summary": "courses list page",
    "description": "Gets the list of outcomes for this assignment",
    "tags": [
     "teacher"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete assignment",
    "tags": [
     "assignments"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   },
   "put": {
    "summary": "save assignment",
    "tags": [
     "assignments"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/assignments/{assignid}/link": {
   "post": {
    "summary": "link assignment",
    "tags": [
     "assignments"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/assignments/{assignid}/outcomes": {
   "post": {
    "summary": "add new outcome",
    "description": "add a new outcome to an assignment",
    "tags": [
     "teacher"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/assignments/{assignid}/outcomes/{outcomeid}": {
   "delete": {
    "summary": "delete outcome",
    "tags": [
     "assignments"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/users": {
   "get": {
    "summary": "get users in a course",
    "description": "Gets the list of users in a course",
    "tags": [
     "teacher"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/users/{userid}": {
   "delete": {
    "summary": "delete user from course",
    "tags": [
     "teacher"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/teacher/courses/{id}/grades": {
   "get": {
    "summary": "get course grades",
    "description": "Gets the course grades for a course",
    "tags": [
     "teacher"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/terms": {
   "get": {
    "summary": "terms list page",
    "description": "Gets the list of all terms in the application",
    "tags": [
     "terms"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   },
   "post": {
    "summary": "create term",
    "tags": [
     "terms"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_lti"
      ]
     }
    ]
   }
  },
  "/api/v1/terms/{id}": {
   "put": {
    "summary": "update term",
    "tags": [
     "terms"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_terms"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete term",
    "tags": [
     "terms"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_terms"
      ]
     }
    ]
   }
  },
  "/api/v1/topics": {
   "get": {
    "summary": "topics list page",
    "description": "Gets the full list of topics",
    "tags": [
     "topics"
    ],
    "security": [
     {
      "bearerAuth": [
       "teacher"
      ]
     }
    ]
   }
  },
  "/api/v1/users": {
   "get": {
    "summary": "users list page",
    "description": "Gets the list of all users in the application",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   },
   "post": {
    "summary": "create user",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   }
  },
  "/api/v1/users/{id}": {
   "get": {
    "summary": "get single user",
    "description": "Gets a single user by ID",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   },
   "put": {
    "summary": "update user",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete user",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "bearerAuth": {
    "type": "http",
    "scheme": "bearer",
    "bearerFormat": "JWT"
   }
  }
 },
 "tags": [
  {
   "name": "api",
   "description": "API routes"
  },
  {
   "name": "auth",
   "description": "Authentication Routes"
  },
  {
   "name": "lti",
   "description": "LTI routes"
  },
  {
   "name": "consumers",
   "description": "Consumers Routes"
  },
  {
   "name": "courses",
   "description": "Courses Routes"
  },
  {
   "name": "lessons",
   "description": "Lessons Routes"
  },
  {
   "name": "levels",
   "description": "Levels Routes"
  },
  {
   "name": "profile",
   "description": "Profile Routes"
  },
  {
   "name": "providers",
   "description": "Providers Routes"
  },
  {
   "name": "roles",
   "description": "Roles Routes"
  },
  {
   "name": "sections",
   "description": "Sections Routes"
  },
  {
   "name": "student",
   "description": "Student Routes"
  },
  {
   "name": "teacher",
   "description": "Teacher Routes"
  },
  {
   "name": "terms",
   "description": "Terms Routes"
  },
  {
   "name": "topics",
   "description": "Topics Routes"
  },
  {
   "name": "users",
   "description": "Users Routes"
  }
 ]
}