/**
 * @file Database schemas
 * @author Russell Feldhausen <russfeld@ksu.edu>
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Consumer:
 *       type: object
 *       required:
 *         - name
 *         - key
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         name:
 *           type: string
 *           description: name of the consumer
 *         lti13:
 *           type: boolean
 *           description: enabled if consumer uses LTI 1.3
 *         key:
 *           type: string
 *           description: the OAuth consumer key or LTI 1.3 unique URL path
 *         client_id:
 *           type: string
 *           description: the LTI 1.3 client ID
 *         platform_id:
 *           type: string
 *           description: the LTI 1.3 platform ID
 *         deployment_id:
 *           type: string
 *           description: the LTI 1.3 deployment ID
 *         keyset_url:
 *           type: string
 *           format: url
 *           description: the URL to request the JWKS
 *         token_url:
 *           type: string
 *           format: url
 *           description: the URL to request a token
 *         auth_url:
 *           type: string
 *           format: url
 *           description: the URL to redirect to for authentication
 *         tc_product:
 *           type: string
 *           description: the product name of the tool consumer
 *         tc_version:
 *           type: string
 *           description: the version of the tool consumer
 *         tc_guid:
 *           type: string
 *           description: the unique GUID of the tool consumer
 *         tc_name:
 *           type: string
 *           description: the internal name of the tool consumer
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the record was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the record was last updated
 *       example:
 *           id: 1
 *           name: Canvas
 *           lti13: true
 *           key: abcdef12345
 *           client_id: 1000000000001
 *           platform_id: https://canvas.instructure.com
 *           deployment_id: superlongstringhere
 *           keyset_url: https://canvas.instructure.com/api/lti/security/jwks
 *           token_url: https://canvas.instructure.com/login/oauth2/token
 *           auth_url: https://canvas.instructure.com/api/lti/authorize_redirect
 *           createdAt: 2025-02-04T15:36:32.000Z
 *           updatedAt: 2025-02-04T15:36:32.000Z
 */
const ConsumerSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("name", value === "" ? null : value);
    },
  },
  lti13: {
    type: Sequelize.BOOLEAN,
    defaultValue: false,
  },
  key: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
  },
  client_id: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  platform_id: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  deployment_id: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  keyset_url: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  token_url: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  auth_url: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  tc_product: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  tc_version: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  tc_guid: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  tc_name: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

const ConsumerKeySchema = {
  key: {
    type: Sequelize.STRING,
    primaryKey: true,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("key", value === "" ? null : value);
    },
  },
  secret: {
    type: Sequelize.STRING,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("secret", value === "" ? null : value);
    },
  },
  public: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  private: {
    type: Sequelize.STRING,
    allowNull: true,
  },
};

const ConsumerLoginSchema = {
  key: {
    type: Sequelize.STRING,
    primaryKey: true,
    allowNull: false,
  },
  state: {
    type: Sequelize.STRING,
    primaryKey: true,
    allowNull: false,
  },
  nonce: {
    type: Sequelize.STRING,
    primaryKey: true,
    allowNull: false,
  },
  iss: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  client_id: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  keyset_url: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

const OauthNonceSchema = {
  key: {
    type: Sequelize.STRING,
    allowNull: false,
    primaryKey: true,
  },
  nonce: {
    type: Sequelize.STRING,
    allowNull: false,
    primaryKey: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

/**
 * @swagger
 * components:
 *   schemas:
 *     Provider:
 *       type: object
 *       required:
 *         - name
 *         - key
 *         - launch_url
 *         - domain
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         name:
 *           type: string
 *           description: name of the provider
 *         lti13:
 *           type: boolean
 *           description: enabled if provider uses LTI 1.3
 *         key:
 *           type: string
 *           description: the OAuth provider key or LTI 1.3 unique URL path
 *         launch_url:
 *           type: string
 *           format: url
 *           description: the URL to send a launch
 *         domain:
 *           type: string
 *           format: hostname
 *           description: the domain of the application
 *         custom:
 *           type: string
 *           format: json
 *           description: a JSON string of custom variables
 *         use_section:
 *           type: boolean
 *           description: whether to use the section ID in the launch
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the record was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the record was last updated
 *       example:
 *           id: 1
 *           name: Learning Tool
 *           lti13: false
 *           key: abcdef12345
 *           launch_url: https://tool.domain/lti/12345abcdef
 *           domain: tool.domain
 *           createdAt: 2025-02-04T15:36:32.000Z
 *           updatedAt: 2025-02-04T15:36:32.000Z
 */
const ProviderSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("name", value === "" ? null : value);
    },
  },
  lti13: {
    type: Sequelize.BOOLEAN,
    defaultValue: false,
  },
  key: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("key", value === "" ? null : value);
    },
  },
  launch_url: {
    type: Sequelize.STRING,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("launch_url", value === "" ? null : value);
    },
  },
  domain: {
    type: Sequelize.STRING,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("domain", value === "" ? null : value);
    },
  },
  custom: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

const ProviderKeySchema = {
  key: {
    type: Sequelize.STRING,
    primaryKey: true,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("key", value === "" ? null : value);
    },
  },
  secret: {
    type: Sequelize.STRING,
    allowNull: false,
    // force null if empty string
    set(value) {
      this.setDataValue("secret", value === "" ? null : value);
    },
  },
};

export {
  ConsumerSchema,
  ConsumerKeySchema,
  ConsumerLoginSchema,
  OauthNonceSchema,
  ProviderSchema,
  ProviderKeySchema,
};
